version: '3'
services:
    user-mysql:
    
        image: mysql:latest
        environment:
            MYSQL_DATABASE: 'springangular'
            MYSQL_USER: 'demo'
            # You can use whatever password you like
            MYSQL_PASSWORD: 'demo'
            # Password for root access
            MYSQL_ROOT_PASSWORD: 'root'
        ports:
            - '3307:3306'
          
        
    user-service:
        build: ./server-user-management
        entrypoint: /wait-for-it.sh user-mysql:3306 -- java -Djava.security.egd=file:/dev/./urandom -Dspring.profiles.active=container -jar app.jar
        links:
            - user-mysql:mysql
        ports:
            - 8080:8080  
        
    course-client:
        build: ./client-user-management
        ports:
            - 4200:80 
