version: '3'
services:
    user-mysql:
    
        image: mysql:latest
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_PASSWORD=root
            - MYSQL_DATABASE=demo
            
        ports:
            - '3307:3306'
          
        
    user-service:
        environment:
            SPRING_DATASOURCE_URL: jdbc:mysql://user-mysql:3306/demo?autoReconnect=true&useSSL=false
            SPRING_DATASOURCE_USERNAME: "root"
            SPRING_DATASOURCE_PASSWORD: "root"
                
        ports:
            - 8082:8082
        build: ./server-user-management
        entrypoint: /wait-for-it.sh user-mysql:3306 -- java -Djava.security.egd=file:/dev/./urandom -Dspring.profiles.active=container -jar app.jar
        depends_on:
            - user-mysql
        
    course-client:
        build: ./client-user-management
        ports:
            - 4200:80 
