version: '3.0'
services:
    user-mysql:
    
        image: mysql:latest
        restart: always
        environment:
            MYSQL_DATABASE: 'springangular'
            MYSQL_USER: 'demo'
            # You can use whatever password you like
            MYSQL_PASSWORD: 'demo'
            # Password for root access
            MYSQL_ROOT_PASSWORD: 'password'
        ports:
            - '3306:3306'
        expose:
            # Opens port 3306 on the container
            - '3306'   
        
    user-service:
        build: ./server-user-management
        entrypoint: /wait-for-it.sh user-mysql:3306 -- java -Djava.security.egd=file:/dev/./urandom -Dspring.profiles.active=container -jar app.jar
        links:
            - user-mysql:mysql
        ports:
            - 8080:8080  
        
    course-client:
        build: ./client-user-management
        ports:
            - 4200:80 
