spring:
  profiles: container
  datasource:
    url: jdbc:mysql://mysqldb:3306/springangular?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false
    username: demo
    password: demo
    initialize: true
    driverClassName: com.mysql.cj.jdbc.Driver
    jpa:
    hibernate:
      ddl-auto: none
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.xml
  application:
    name: server-side
