spring:
  profiles: container
  datasource:
    url: jdbc:mysql://34.121.42.234:3306/springangular?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false
    username: demo
    password: demo
    initialize: true
